<a href="https://colab.research.google.com/github/majorquev/DBDC_202404_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto).
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [6]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
l1 <- list(num = c(1,1,2,3),
           letras = c("X","Y","Z"),
           pl = "Miguel jorquera",
           mat = diag(1:3),
           sub_l = list(a = Sys.Date(),
                        v = c(T,T,F)))

In [19]:
length(l1)
class(l1)

[1] 5

[1] "list"

In [10]:
l1

$num
[1] 1 1 2 3

$letras
[1] "X" "Y" "Z"

$pl
[1] "Miguel jorquera"

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$sub_l
$sub_l$a
[1] "2024-04-19"

$sub_l$v
[1]  TRUE  TRUE FALSE

In [11]:
# estructura
str(l1)

List of 5
 $ num   : num [1:4] 1 1 2 3
 $ letras: chr [1:3] "X" "Y" "Z"
 $ pl    : chr "Miguel jorquera"
 $ mat   : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_l :List of 2
  ..$ a: Date[1:1], format: "2024-04-19"
  ..$ v: logi [1:3] TRUE TRUE FALSE


In [14]:
# Podemos guardar los objetos en slots con nombres
l0 <- list(1,"B",1:4)
l0

[[1]]
[1] 1

[[2]]
[1] "B"

[[3]]
[1] 1 2 3 4

In [15]:
str(l0)

List of 3
 $ : num 1
 $ : chr "B"
 $ : int [1:4] 1 2 3 4


In [17]:
# Podemos combinar listas
l2 <- c(l1,l0)
str(l2)

List of 8
 $ num   : num [1:4] 1 1 2 3
 $ letras: chr [1:3] "X" "Y" "Z"
 $ pl    : chr "Miguel jorquera"
 $ mat   : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_l :List of 2
  ..$ a: Date[1:1], format: "2024-04-19"
  ..$ v: logi [1:3] TRUE TRUE FALSE
 $       : num 1
 $       : chr "B"
 $       : int [1:4] 1 2 3 4


In [18]:
# Acceso mediante posición
l1[2]

$letras
[1] "X" "Y" "Z"

In [20]:
class(l1[2])

[1] "list"

In [21]:
l1[2:5]

$letras
[1] "X" "Y" "Z"

$pl
[1] "Miguel jorquera"

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$sub_l
$sub_l$a
[1] "2024-04-19"

$sub_l$v
[1]  TRUE  TRUE FALSE

In [24]:
l1[4][2,] # R no lo entiende pues es una lista con la matriz

ERROR: Error in l1[4][2, ]: incorrect number of dimensions


In [27]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l1[4]
l1[[4]]

class(l1[4])
class(l1[[4]])

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

[1] "list"

[1] "matrix" "array"

In [28]:
# Queremos rescatar la fila 2 de la matriz que està en la pos 4 de la lista l1

l1[[4]][2,]

[1] 0 2 0

In [29]:
str(l1)

List of 5
 $ num   : num [1:4] 1 1 2 3
 $ letras: chr [1:3] "X" "Y" "Z"
 $ pl    : chr "Miguel jorquera"
 $ mat   : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_l :List of 2
  ..$ a: Date[1:1], format: "2024-04-19"
  ..$ v: logi [1:3] TRUE TRUE FALSE


In [40]:
# de la lista l1[[5]], quieo el vector que está en el slot llamado "v" (segundo elemento)
l1[[5]] # Esto es el objeto que está enb la posición 5 (es la lista llamada sub_l)


$a
[1] "2024-04-19"

$v
[1]  TRUE  TRUE FALSE

In [39]:
l1[[5]][[2]] # es el vector de la lista l1[[5]]


[1]  TRUE  TRUE FALSE

In [41]:
l1[[5]][2] # Es la lista con el vector.

$v
[1]  TRUE  TRUE FALSE

In [36]:
l1[5] # Esto es la lista con el objeto que está enb la posición 5 (es la lista llamada sub_l)

$sub_l
$sub_l$a
[1] "2024-04-19"

$sub_l$v
[1]  TRUE  TRUE FALSE

In [42]:
# Acceso mediante nombre
# si queremos acceder a la matriz mat
l1["mat"] # retorna la lista con la matriz


$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [43]:
l1[["mat"]] # retorna la matriz

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [45]:
# de la lista sub_l, quieo el vector que está en el slot llamado "v"
l1[["sub_l"]]["v"] # Retorna la lista con el vector

$v
[1]  TRUE  TRUE FALSE

In [46]:
# de la lista sub_l, quieo el vector que está en el slot llamado "v"  # Retorna el vector

[1]  TRUE  TRUE FALSE

In [51]:
# acceso vía "$"
l1$mat # Es un atajo para l1[["mat"]], retorna directamente el objeto del slot





[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [55]:
# de la lista sub_l, quieo el vector que está en el slot llamado "v"
l1$sub_l$v
l1[["sub_l"]][["v"]]
l1[[5]][[2]]

[1]  TRUE  TRUE FALSE

[1]  TRUE  TRUE FALSE

[1]  TRUE  TRUE FALSE

In [50]:
l2$

NULL

In [59]:
# para saber el largo de la lista/vector
length(l1)
# Para obtener los nombres de la lista
names(l1)
# si quisiéramos renombrar los slots:
names(l1)[5] <- "sub_LISTA"

[1] 5

[1] "num"    "letras" "pl"     "mat"    "sub_l"

In [60]:
str(l1)

List of 5
 $ num      : num [1:4] 1 1 2 3
 $ letras   : chr [1:3] "X" "Y" "Z"
 $ pl       : chr "Miguel jorquera"
 $ mat      : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_LISTA:List of 2
  ..$ a: Date[1:1], format: "2024-04-19"
  ..$ v: logi [1:3] TRUE TRUE FALSE


In [62]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
l1[["nuevo"]] <- c("w","h")

In [63]:
str(l1)

List of 6
 $ num      : num [1:4] 1 1 2 3
 $ letras   : chr [1:3] "X" "Y" "Z"
 $ pl       : chr "Miguel jorquera"
 $ mat      : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_LISTA:List of 2
  ..$ a: Date[1:1], format: "2024-04-19"
  ..$ v: logi [1:3] TRUE TRUE FALSE
 $ nuevo    : chr [1:2] "w" "h"


In [65]:
l1$otro <- "NUEVO TEXTO"

In [66]:
str(l1)

List of 7
 $ num      : num [1:4] 1 1 2 3
 $ letras   : chr [1:3] "X" "Y" "Z"
 $ pl       : chr "Miguel jorquera"
 $ mat      : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_LISTA:List of 2
  ..$ a: Date[1:1], format: "2024-04-19"
  ..$ v: logi [1:3] TRUE TRUE FALSE
 $ nuevo    : chr [1:2] "w" "h"
 $ otro     : chr "NUEVO TEXTO"


In [67]:
# podemos modificar elementos dentro de un slot
l1$mat[3,3] <- 99


In [68]:
l1$mat

[,1] [,2] [,3]
[1,] 1    0     0  
[2,] 0    2     0  
[3,] 0    0    99

### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí.

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.

 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [ ]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)



In [ ]:
# Acceso a columnas de un data.frame
## Igual que en una lista



In [ ]:
##  Ganamos acceso como matriz
# segundafila de df


# segunda columna y segunda fila




In [ ]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista


In [ ]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3

# Referenciando el nombre de las columnas


In [ ]:
# Referenciando las posiciones de las columnas


In [ ]:
# Se mantiene la lógica de acceso a los sots de una lista.
